//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebcamMotion.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebcamMotion.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        internal static string appSettings {
            get {
                return ResourceManager.GetString("appSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application started.
        /// </summary>
        internal static string appStarted {
            get {
                return ResourceManager.GetString("appStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application stoped.
        /// </summary>
        internal static string appStoped {
            get {
                return ResourceManager.GetString("appStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin detection on startup.
        /// </summary>
        internal static string beginDetection {
            get {
                return ResourceManager.GetString("beginDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing settings.
        /// </summary>
        internal static string capturingSettings {
            get {
                return ResourceManager.GetString("capturingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing started.
        /// </summary>
        internal static string capturingStarted {
            get {
                return ResourceManager.GetString("capturingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing stoped.
        /// </summary>
        internal static string capturingStoped {
            get {
                return ResourceManager.GetString("capturingStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string device {
            get {
                return ResourceManager.GetString("device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload exception.
        /// </summary>
        internal static string fileUploadException {
            get {
                return ResourceManager.GetString("fileUploadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Drive.
        /// </summary>
        internal static string googleDrive {
            get {
                return ResourceManager.GetString("googleDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray on startup.
        /// </summary>
        internal static string minimizeToTray {
            get {
                return ResourceManager.GetString("minimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion detected.
        /// </summary>
        internal static string motionDetected {
            get {
                return ResourceManager.GetString("motionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion sensor sensitivity.
        /// </summary>
        internal static string motionSensorSensitivity {
            get {
                return ResourceManager.GetString("motionSensorSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Window.
        /// </summary>
        internal static string previewWindow {
            get {
                return ResourceManager.GetString("previewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run with Windows.
        /// </summary>
        internal static string runWithWindows {
            get {
                return ResourceManager.GetString("runWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save copies to (will be deleted after send).
        /// </summary>
        internal static string saveCopiesTo {
            get {
                return ResourceManager.GetString("saveCopiesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save frame to file.
        /// </summary>
        internal static string saveFrameToFile {
            get {
                return ResourceManager.GetString("saveFrameToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save snapshots to.
        /// </summary>
        internal static string saveTo {
            get {
                return ResourceManager.GetString("saveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected device.
        /// </summary>
        internal static string selectedDevice {
            get {
                return ResourceManager.GetString("selectedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings apply error.
        /// </summary>
        internal static string settingsApplyError {
            get {
                return ResourceManager.GetString("settingsApplyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show date and time.
        /// </summary>
        internal static string showDateTime {
            get {
                return ResourceManager.GetString("showDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show preview.
        /// </summary>
        internal static string showPreview {
            get {
                return ResourceManager.GetString("showPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshots interval.
        /// </summary>
        internal static string snapshotsInterval {
            get {
                return ResourceManager.GetString("snapshotsInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture snapshots only by interval (disable motion sensor).
        /// </summary>
        internal static string snapshotsOnlyByInterval {
            get {
                return ResourceManager.GetString("snapshotsOnlyByInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing start delay.
        /// </summary>
        internal static string startDelay {
            get {
                return ResourceManager.GetString("startDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start delayed to.
        /// </summary>
        internal static string startDelayedTo {
            get {
                return ResourceManager.GetString("startDelayedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string telegramCode {
            get {
                return ResourceManager.GetString("telegramCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get code.
        /// </summary>
        internal static string telegramGetCode {
            get {
                return ResourceManager.GetString("telegramGetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string telegramLogin {
            get {
                return ResourceManager.GetString("telegramLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send motion detection notifications to Telegram.
        /// </summary>
        internal static string telegramNotify {
            get {
                return ResourceManager.GetString("telegramNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number (example 79991234567).
        /// </summary>
        internal static string telegramPhoneNumber {
            get {
                return ResourceManager.GetString("telegramPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session status.
        /// </summary>
        internal static string telegramSessionStatus {
            get {
                return ResourceManager.GetString("telegramSessionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string telegramStatusActive {
            get {
                return ResourceManager.GetString("telegramStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking.
        /// </summary>
        internal static string telegramStatusChecking {
            get {
                return ResourceManager.GetString("telegramStatusChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not active.
        /// </summary>
        internal static string telegramStatusInactive {
            get {
                return ResourceManager.GetString("telegramStatusInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file to Google Drive. Path to file.
        /// </summary>
        internal static string uploadFileToGoogleDrive {
            get {
                return ResourceManager.GetString("uploadFileToGoogleDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload copies to Google Drive.
        /// </summary>
        internal static string uploadToGoogleDrive {
            get {
                return ResourceManager.GetString("uploadToGoogleDrive", resourceCulture);
            }
        }
    }
}
